# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMatrix <- function(x, idx) {
    .Call('bamsignals_getMatrix', PACKAGE = 'bamsignals', x, idx)
}

getVector <- function(x, idx) {
    .Call('bamsignals_getVector', PACKAGE = 'bamsignals', x, idx)
}

getSubset <- function(x, idxs) {
    .Call('bamsignals_getSubset', PACKAGE = 'bamsignals', x, idxs)
}

asList <- function(x) {
    .Call('bamsignals_asList', PACKAGE = 'bamsignals', x)
}

fastWidth <- function(x) {
    .Call('bamsignals_fastWidth', PACKAGE = 'bamsignals', x)
}

pileup_core <- function(gr, bampath, mapqual = 0L, binsize = 1L, shift = 0L, ss = FALSE, pe = FALSE, pe_mid = FALSE, maxfraglength = 1000L, maxgap = 16385L) {
    .Call('bamsignals_pileup_core', PACKAGE = 'bamsignals', gr, bampath, mapqual, binsize, shift, ss, pe, pe_mid, maxfraglength, maxgap)
}

coverage_core <- function(gr, bampath, mapqual = 0L, pe = FALSE, maxfraglength = 1000L, maxgap = 16385L) {
    .Call('bamsignals_coverage_core', PACKAGE = 'bamsignals', gr, bampath, mapqual, pe, maxfraglength, maxgap)
}

writeSamAsBamAndIndex <- function(sampath, bampath) {
    .Call('bamsignals_writeSamAsBamAndIndex', PACKAGE = 'bamsignals', sampath, bampath)
}

