# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkList <- function(l, ss) {
    .Call('bamsignals_checkList', PACKAGE = 'bamsignals', l, ss)
}

fastWidth <- function(l, ss) {
    .Call('bamsignals_fastWidth', PACKAGE = 'bamsignals', l, ss)
}

pileup_core <- function(bampath, gr, mapqual = 0L, binsize = 1L, shift = 0L, ss = FALSE, mask = 0L, pe_mid = FALSE, maxfraglength = 1000L, minfraglength = 0L, maxgap = 16385L) {
    .Call('bamsignals_pileup_core', PACKAGE = 'bamsignals', bampath, gr, mapqual, binsize, shift, ss, mask, pe_mid, maxfraglength, minfraglength, maxgap)
}

coverage_core <- function(bampath, gr, mapqual = 0L, mask = 0L, tspan = FALSE, maxfraglength = 1000L, minfraglength = 0L, maxgap = 16385L) {
    .Call('bamsignals_coverage_core', PACKAGE = 'bamsignals', bampath, gr, mapqual, mask, tspan, maxfraglength, minfraglength, maxgap)
}

writeSamAsBamAndIndex <- function(sampath, bampath) {
    .Call('bamsignals_writeSamAsBamAndIndex', PACKAGE = 'bamsignals', sampath, bampath)
}

