# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMatrix <- function(csig, idx) {
    .Call('bamsignals_getMatrix', PACKAGE = 'bamsignals', csig, idx)
}

getVector <- function(csig, idx) {
    .Call('bamsignals_getVector', PACKAGE = 'bamsignals', csig, idx)
}

getSubset <- function(csig, idxs) {
    .Call('bamsignals_getSubset', PACKAGE = 'bamsignals', csig, idxs)
}

asList <- function(csig) {
    .Call('bamsignals_asList', PACKAGE = 'bamsignals', csig)
}

fastWidth <- function(csig) {
    .Call('bamsignals_fastWidth', PACKAGE = 'bamsignals', csig)
}

pileup_core <- function(gr, bampath, mapqual = 0L, binsize = 1L, shift = 0L, ss = FALSE, pe = FALSE, pe_mid = FALSE, maxfraglength = 1000L, maxgap = 16385L) {
    .Call('bamsignals_pileup_core', PACKAGE = 'bamsignals', gr, bampath, mapqual, binsize, shift, ss, pe, pe_mid, maxfraglength, maxgap)
}

coverage_core <- function(gr, bampath, mapqual = 0L, pe = FALSE, maxfraglength = 1000L, maxgap = 16385L) {
    .Call('bamsignals_coverage_core', PACKAGE = 'bamsignals', gr, bampath, mapqual, pe, maxfraglength, maxgap)
}

subsetCounts <- function(counts, start, width, strand) {
    .Call('bamsignals_subsetCounts', PACKAGE = 'bamsignals', counts, start, width, strand)
}

countInSubset <- function(counts, start, width) {
    .Call('bamsignals_countInSubset', PACKAGE = 'bamsignals', counts, start, width)
}

writeSamAsBam <- function(sampath, bampath) {
    .Call('bamsignals_writeSamAsBam', PACKAGE = 'bamsignals', sampath, bampath)
}

